name: marketly
description: A new Flutter project.

# Prevent publishing to pub.dev
publish_to: 'none'

# Version info
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS-style
  cupertino_icons: ^1.0.8

  # Networking package
  dio: ^5.9.0

  # Lottie animations
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

